### ISSUE TITLE
Some characters not shown in Windows 7

### ISSUE THREAD

**Issue by rugk** [klorenz/atom-character-table#7]
![charactertablewindows](https://cloud.githubusercontent.com/assets/11966684/9529340/eace1dec-4cf9-11e5-83fe-07e5d62fac50.png)

I think you have the same or a similar issue like https://github.com/atom/autocomplete-emojis/issues/4 here.

**Comment by klorenz** [comment]
Hi rugk,
I have no influence on this.  This depends on the electron build (see http://electron.atom.io).
Regards, Kiwi
